name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: |
              ${{secrets.BITBUCKETPRIVATEKEY}}

    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    - name: checkout Repo
      env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: git clone git@bitbucket.org:energyconservatory/tecconfig.git

